Improved Shortcut Scheme
zaps166/QMPlay2 pull request #494
Opened 2022-04-05 14:35 UTC by zo-shin

Made all the shortcuts separated by moving them to brackets and other minor changes.
close #492

2022-04-24 11:21 UTC, zaps166 requested changes

2022-04-24 11:21 UTC, zaps166 commented on src/gui/MainWidget.cpp
> +﻿/*
Please don't add UTF-8 BOM.

2022-04-24 22:32 UTC, merged

2022-04-24 22:33 UTC, zaps166 commented
ehh doesn't compile

2022-04-24 22:41 UTC, zaps166 commented
I fixed XML files, but it looks very bad:

![Screenshot_20220425_004045](https://user-images.githubusercontent.com/6239090/164999724-7a5f57a2-93f4-4f1f-b6b3-394345205fb6.png)

Reverted.

2022-04-25 04:20 UTC, zo-shin commented
What do you think is the problem? Is it OK if I just make changes to the language TS files only?

2022-04-25 10:08 UTC, zaps166 commented
Changes to TS files are not a problem. I uploaded a screenshot of menu bar - it looks vary bad with brackets at the end: `Help(H)`, etc... Same with menu items.

2022-04-25 12:25 UTC, zo-shin commented
If that looks bad, do you have any better solution about the issue? It seems a common way to deal with shortcuts.

2022-04-27 23:26 UTC, zaps166 commented
Maybe add it only for Chinese translations?

2022-04-30 06:45 UTC, zo-shin commented
All the languages should be solved in the same way, not only Chinese.

2022-04-30 10:36 UTC, zaps166 commented
> All the languages should be solved in the same way, not only Chinese.

Chinese, Japanese. Example:


- QtCreator Chinese
![Screenshot_20220430_123356](https://user-images.githubusercontent.com/6239090/166102035-25fe19e5-7364-4b0b-9056-66b1ae3b68f7.png)

- QtCreator English
![Screenshot_20220430_123427](https://user-images.githubusercontent.com/6239090/166102048-e1835f97-78bf-41ae-83b0-85028077198d.png)